### ISSUE TITLE
Extra packages needed

### ISSUE THREAD

**Issue by gijs** [lizardsystem/lizard-efcis#26]
We're doing some advanced in-DB statistics in this project. 
Computing the boxplot values for example.

For this we need the following APT packages installed on the database server:
- postgresql-plpython-9.3
- python-numpy

Also, as user `postgres`, issue the following command (on the database server):

```
$ createlang plpythonu efcis_site
```

**Comment by gijs** [comment]
This is high priority - cannot merge my PR without it.

**Comment by reinout** [comment]
Two quick quick thoughts from the UK:
- Do we really need it? Can't it simply be done in python code on the client? We're grabbing all the data already... I'd normally prefer to keep the DB as-is.
- How do we use it from within django rest framework, actually? Probably some custom sql injected into the query? If so, and _if_ we want to do it this way: there are very nice ways to do this nicely pythonic with some new 1.7/1.8 django thingies. So... we _could_ do some extra work later on to really unlock the plpython/numpy stuff :-)

**Comment by gijs** [comment]
Hi Reinout

Interesting. We could keep it out of the DB, but the way I've set it up now is pretty clean imho ;)

I've not yet submitted the PR but this is how it looks in views.py:

```
from django.db import connection

cursor = connection.cursor()
cursor.execute("SELECT min, max, median, q1, q3 FROM ( \
    SELECT locatie_id, (boxplot(waarde_n::numeric)).* \
    FROM lizard_efcis_opname \
    WHERE locatie_id=%s AND waarde_n IS NOT NULL \
    GROUP BY locatie_id) AS boxplot", [locatie])
percentile = dictfetchall(cursor)
```

percentile contains the stats and gets returned by Django Rest Framework.

This is the PL/Python function (along with an AGGREGATE and a TYPE):

```
    CREATE OR REPLACE FUNCTION _final_boxplot(strarr numeric[])
       RETURNS boxplot_values AS
    $$
        import numpy as np
        x = strarr
        a = eval(str(x))

        a.sort()
        i = len(a)

        p10 = np.percentile(a, 10)
        p90 = np.percentile(a, 90)
        mean = np.mean(a)
        min = a[0]
        max = a[-1]
        median = np.median(a)
        q1 = np.percentile(a, 25)
        q3 = np.percentile(a, 75)

        return (min, q1, median, q3, max, p10, p90, mean)
    $$
    LANGUAGE 'plpythonu' IMMUTABLE;
```

**Comment by gijs** [comment]
Also, we could use `.raw()` instead of cursor.execute to keep it a bit more Pythonic, but I like the idea of doing as much as possible in SQL (although you could argue if this is still SQL)

It's the back-end, so it's your call ;)

**Comment by gijs** [comment]
![screen shot 2015-06-04 at 15 40 02](https://cloud.githubusercontent.com/assets/7193/7985290/06b0b87e-0ad0-11e5-85a6-e8b74537203a.jpg)
^^ This is the output for one location which takes basically no time at all. For the entire DB it takes 1,5 second.

**Comment by gijs** [comment]
Now have a working Boxplot API endpoint as well:

![screen shot 2015-06-04 at 16 00 24](https://cloud.githubusercontent.com/assets/7193/7985702/e4d119d0-0ad2-11e5-83cd-994a7a12f7e4.jpg)

**Comment by reinout** [comment]
You say it is pretty clean. This means, I presume, that you're doing the "create and replace" in a nice and clean migration step? :-)

Hm... Raw sql... I'm not good in sql. And we need to make sure the values we put into the query are coming from the model, _not_ from user input (=directly from the GET parameters).

How easy is it to do it in python? It are just a few data points per graph, right? So any speed advantage from doing it on the database will be neglegible. At least, I assume that speed is the reason that you normally do something like this on the database?

I'm pushing back a bit because this request also means we have to install this postgres extension on the production database server later on. And that we have to migrate a postgres extension when we move from ubuntu 14.04LTS to 16.04LTS.

So... what could make this valuable enough to do is when there's really a lot of data that you'd otherwise have to grab from the database. If it is only for calculating the min/max/median for 12 data points: I'd say "no".

**Comment by gijs** [comment]
Not THAT clean, no :)

What I consider valuable is that being able to do `SELECT boxplot(values).*` keeps statistical code in one place, ie gets out of the way. Is there a way to do it using the ORM?

Agree on all your points though, I personally don't care where the code lives as long as it works fast and well.

I'll try doing it all in `views.py`. Do we have Numpy on the production server?

**Comment by reinout** [comment]
Numpy? Probably. Add it to the `[sysegg]` part to make sure it must be installed. Lizard5 is on that server, so I'm 99.9% sure.

Well, I could point at http://reinout.vanrees.org/weblog/2015/06/03/02-views.html

Normally you either put something in models.py or views.py. The way you talk about it, it sounds like "business logic", so models.py. In this case, I'd guess I'd just put it in views.py.

Putting it in the database is a very weird way of adding a new python module called "statistics.py" :-)

**Comment by reinout** [comment]
Quickest solution: you've got working numpy code, so just give that to @AlexandrSeleznev and have him put it somewhere in the views.py?

**Comment by gijs** [comment]
I asked Alexandr.
