### ISSUE TITLE
FieldError at /api/opnames/

### ISSUE THREAD

**Issue by gijs** [lizardsystem/lizard-efcis#3]
When using GET parameters to filter: `?locatie=NL14-20001&page=1&page_size=1000&start_date=1-1-2014&end_date=31-1-2014`
![screen shot 2015-03-03 at 16 56 47](https://cloud.githubusercontent.com/assets/7193/6466220/5921effe-c1c6-11e4-8234-d02d64cbb8f1.jpg)

**Comment by reinout** [comment]
Ik zie 'em nu ook verschijnen als ik een einddatum invul. Als je die leeg laat doet 'ie het wel.

Zie zou gauw niet waar de fout vandaan komt; ik moet nu naar huis ;-)

**Comment by gijs** [comment]
No problem!

**Comment by reinout** [comment]
Fixed in af8a4f1e24af01ac8d6f82fd9ac2c94a9a61f338
